const comments = [
    { "id": 1, "post_id": 1, "author_id": 1, "body": "Comment body 1." },
    { "id": 2, "post_id": 2, "author_id": 1, "body": "Comment body 2." },
    { "id": 3, "post_id": 3, "author_id": 1, "body": "Comment body 3." },
    { "id": 4, "post_id": 4, "author_id": 1, "body": "Comment body 4." },
    { "id": 5, "post_id": 5, "author_id": 1, "body": "Comment body 5." },
    { "id": 6, "post_id": 6, "author_id": 1, "body": "Comment body 6." },
    { "id": 7, "post_id": 7, "author_id": 1, "body": "Comment body 7." },
    { "id": 8, "post_id": 8, "author_id": 1, "body": "Comment body 8." },
    { "id": 9, "post_id": 9, "author_id": 1, "body": "Comment body 9." },
    { "id": 10, "post_id": 10, "author_id": 1, "body": "Comment body 10." },
    { "id": 11, "post_id": 1, "author_id": 1, "body": "Comment body 11." },
    { "id": 12, "post_id": 2, "author_id": 1, "body": "Comment body 12." },
    { "id": 13, "post_id": 3, "author_id": 1, "body": "Comment body 13." },
    { "id": 14, "post_id": 4, "author_id": 1, "body": "Comment body 14." },
    { "id": 15, "post_id": 5, "author_id": 1, "body": "Comment body 15." },
    { "id": 16, "post_id": 6, "author_id": 1, "body": "Comment body 16." },
    { "id": 17, "post_id": 7, "author_id": 1, "body": "Comment body 17." },
    { "id": 18, "post_id": 8, "author_id": 1, "body": "Comment body 18." },
    { "id": 19, "post_id": 9, "author_id": 1, "body": "Comment body 19." },
    { "id": 20, "post_id": 10, "author_id": 1, "body": "Comment body 20." },
    { "id": 21, "post_id": 1, "author_id": 1, "body": "Comment body 21." },
    { "id": 22, "post_id": 2, "author_id": 1, "body": "Comment body 22." },
    { "id": 23, "post_id": 3, "author_id": 1, "body": "Comment body 23." },
    { "id": 24, "post_id": 4, "author_id": 1, "body": "Comment body 24." },
    { "id": 25, "post_id": 5, "author_id": 1, "body": "Comment body 25." },
    { "id": 26, "post_id": 6, "author_id": 1, "body": "Comment body 26." },
    { "id": 27, "post_id": 7, "author_id": 1, "body": "Comment body 27." },
    { "id": 28, "post_id": 8, "author_id": 1, "body": "Comment body 28." },
    { "id": 29, "post_id": 9, "author_id": 1, "body": "Comment body 29." },
    { "id": 30, "post_id": 10, "author_id": 1, "body": "Comment body 30." },
    { "id": 31, "post_id": 1, "author_id": 1, "body": "Comment body 31." },
    { "id": 32, "post_id": 2, "author_id": 1, "body": "Comment body 32." },
    { "id": 33, "post_id": 3, "author_id": 1, "body": "Comment body 33." },
    { "id": 34, "post_id": 4, "author_id": 1, "body": "Comment body 34." },
    { "id": 35, "post_id": 5, "author_id": 1, "body": "Comment body 35." },
    { "id": 36, "post_id": 6, "author_id": 1, "body": "Comment body 36." },
    { "id": 37, "post_id": 7, "author_id": 1, "body": "Comment body 37." },
    { "id": 38, "post_id": 8, "author_id": 1, "body": "Comment body 38." },
    { "id": 39, "post_id": 9, "author_id": 1, "body": "Comment body 39." },
    { "id": 40, "post_id": 10, "author_id": 1, "body": "Comment body 40." }
]

export default comments;