const posts = [
    { "id": 1, "category": {"id": 1, "name": "Кофе и еда"}, "author_id": 1, "name": "Post 1", "body": "Body of post 1", "likes": 5, "dislikes": 1 },
    { "id": 2, "category": {"id": 1, "name": "Кофе и еда"}, "author_id": 2, "name": "Post 2", "body": "Body of post 2", "likes": 3, "dislikes": 2 },
    { "id": 3, "category": {"id": 1, "name": "Кофе и еда"}, "author_id": 3, "name": "Post 3", "body": "Body of post 3", "likes": 12, "dislikes": 4 },
    { "id": 4, "category": {"id": 1, "name": "Кофе и еда"}, "author_id": 4, "name": "Post 4", "body": "Body of post 4", "likes": 7, "dislikes": 0 },
    { "id": 5, "category": {"id": 1, "name": "Кофе и еда"}, "author_id": 5, "name": "Post 5", "body": "Body of post 5", "likes": 8, "dislikes": 1 },
    { "id": 6, "category": {"id": 1, "name": "Кофе и еда"}, "author_id": 6, "name": "Post 6", "body": "Body of post 6", "likes": 2, "dislikes": 0 },
    { "id": 7, "category": {"id": 1, "name": "Кофе и еда"}, "author_id": 7, "name": "Post 7", "body": "Body of post 7", "likes": 10, "dislikes": 5 },
    { "id": 8, "category": {"id": 1, "name": "Кофе и еда"}, "author_id": 8, "name": "Post 8", "body": "Body of post 8", "likes": 6, "dislikes": 2 },
    { "id": 9, "category": {"id": 1, "name": "Кофе и еда"}, "author_id": 9, "name": "Post 9", "body": "Body of post 9", "likes": 0, "dislikes": 0 },
    { "id": 10, "category": {"id": 1, "name": "Кофе и еда"}, "author_id": 10, "name": "Post 10", "body": "Body of post 10", "likes": 15, "dislikes": 1 },
    { "id": 11, "category": {"id": 1, "name": "Кофе и еда"}, "author_id": 11, "name": "Post 11", "body": "Body of post 11", "likes": 4, "dislikes": 3 },
    { "id": 12, "category": {"id": 7, "name": "Вопрос"}, "author_id": 12, "name": "Post 12", "body": "Body of post 12", "likes": 3, "dislikes": 1 },
    { "id": 13, "category": {"id": 7, "name": "Вопрос"}, "author_id": 13, "name": "Post 13", "body": "Body of post 13", "likes": 9, "dislikes": 1 },
    { "id": 14, "category": {"id": 7, "name": "Вопрос"}, "author_id": 14, "name": "Post 14", "body": "Body of post 14", "likes": 6, "dislikes": 2 },
    { "id": 15, "category": {"id": 7, "name": "Вопрос"}, "author_id": 15, "name": "Post 15", "body": "Body of post 15", "likes": 11, "dislikes": 0 },
    { "id": 16, "category": {"id": 7, "name": "Вопрос"}, "author_id": 16, "name": "Post 16", "body": "Body of post 16", "likes": 1, "dislikes": 1 },
    { "id": 17, "category": {"id": 7, "name": "Вопрос"}, "author_id": 17, "name": "Post 17", "body": "Body of post 17", "likes": 0, "dislikes": 2 },
    { "id": 18, "category": {"id": 7, "name": "Вопрос"}, "author_id": 18, "name": "Post 18", "body": "Body of post 18", "likes": 13, "dislikes": 0 },
    { "id": 19, "category": {"id": 7, "name": "Вопрос"}, "author_id": 19, "name": "Post 19", "body": "Body of post 19", "likes": 2, "dislikes": 4 },
    { "id": 20, "category": {"id": 7, "name": "Вопрос"}, "author_id": 20, "name": "Post 20", "body": "Body of post 20", "likes": 5, "dislikes": 1 },
    { "id": 21, "category": {"id": 7, "name": "Вопрос"}, "author_id": 1, "name": "Post 21", "body": "Body of post 21", "likes": 9, "dislikes": 2 },
    { "id": 22, "category": {"id": 7, "name": "Вопрос"}, "author_id": 2, "name": "Post 22", "body": "Body of post 22", "likes": 4, "dislikes": 0 },
    { "id": 23, "category": {"id": 7, "name": "Вопрос"}, "author_id": 3, "name": "Post 23", "body": "Body of post 23", "likes": 6, "dislikes": 3 },
    { "id": 24, "category": {"id": 7, "name": "Вопрос"}, "author_id": 4, "name": "Post 24", "body": "Body of post 24", "likes": 8, "dislikes": 1 },
    { "id": 25, "category": {"id": 7, "name": "Вопрос"}, "author_id": 5, "name": "Post 25", "body": "Body of post 25", "likes": 2, "dislikes": 0 },
    { "id": 26, "category": {"id": 7, "name": "Вопрос"}, "author_id": 6, "name": "Post 26", "body": "Body of post 26", "likes": 12, "dislikes": 1 },
    { "id": 27, "category": 3, "author_id": 7, "name": "Post 27", "body": "Body of post 27", "likes": 3, "dislikes": 2 },
    { "id": 28, "category": 4, "author_id": 8, "name": "Post 28", "body": "Body of post 28", "likes": 5, "dislikes": 1 },
    { "id": 29, "category": 5, "author_id": 9, "name": "Post 29", "body": "Body of post 29", "likes": 7, "dislikes": 2 },
    { "id": 30, "category": 6, "author_id": 10, "name": "Post 30", "body": "Body of post 30", "likes": 1, "dislikes": 1 },
    { "id": 31, "category": 7, "author_id": 11, "name": "Post 31", "body": "Body of post 31", "likes": 10, "dislikes": 4 },
    { "id": 32, "category": 8, "author_id": 12, "name": "Post 32", "body": "Body of post 32", "likes": 6, "dislikes": 3 },
    { "id": 33, "category": 1, "author_id": 13, "name": "Post 33", "body": "Body of post 33", "likes": 4, "dislikes": 2 },
    { "id": 34, "category": 2, "author_id": 14, "name": "Post 34", "body": "Body of post 34", "likes": 11, "dislikes": 0 },
    { "id": 35, "category": 3, "author_id": 15, "name": "Post 35", "body": "Body of post 35", "likes": 0, "dislikes": 0 },
    { "id": 36, "category": 4, "author_id": 16, "name": "Post 36", "body": "Body of post 36", "likes": 2, "dislikes": 2 },
    { "id": 37, "category": 5, "author_id": 17, "name": "Post 37", "body": "Body of post 37", "likes": 13, "dislikes": 5 },
    { "id": 38, "category": 6, "author_id": 18, "name": "Post 38", "body": "Body of post 38", "likes": 5, "dislikes": 2 },
    { "id": 39, "category": 7, "author_id": 19, "name": "Post 39", "body": "Body of post 39", "likes": 7, "dislikes": 1 },
    { "id": 40, "category": 8, "author_id": 20, "name": "Post 40", "body": "Body of post 40", "likes": 9, "dislikes": 3 },
    { "id": 1, "category": {"id": 5, "name": "Препод"}, "author_id": 1, "name": "Грачев Д. А.", "body": "Спокойный, уравновешенный препод, на лекциях дает очень структурированный материал. Зачастую не пускает в аудиторию при опоздании более чем на 15 минут. В начале обучения может быть очень тяжело и непонятно, но к преподу нужно привыкнуть", "likes": 5, "dislikes": 1 },
    { "id": 2, "category": {"id": 5, "name": "Препод"}, "author_id": 2, "name": "Post 2", "body": "Body of post 2", "likes": 3, "dislikes": 2 },
    { "id": 3, "category": {"id": 5, "name": "Препод"}, "author_id": 3, "name": "Post 3", "body": "Body of post 3", "likes": 12, "dislikes": 4 },
    { "id": 4, "category": {"id": 5, "name": "Препод"}, "author_id": 4, "name": "Post 4", "body": "Body of post 4", "likes": 7, "dislikes": 0 },
    { "id": 5, "category": {"id": 5, "name": "Препод"}, "author_id": 5, "name": "Post 5", "body": "Body of post 5", "likes": 8, "dislikes": 1 },
    { "id": 6, "category": {"id": 5, "name": "Препод"}, "author_id": 6, "name": "Post 6", "body": "Body of post 6", "likes": 2, "dislikes": 0 },
    { "id": 7, "category": {"id": 5, "name": "Препод"}, "author_id": 7, "name": "Post 7", "body": "Body of post 7", "likes": 10, "dislikes": 5 },
    { "id": 8, "category": {"id": 5, "name": "Препод"}, "author_id": 8, "name": "Post 8", "body": "Body of post 8", "likes": 6, "dislikes": 2 },
    { "id": 9, "category": {"id": 5, "name": "Препод"}, "author_id": 9, "name": "Post 9", "body": "Body of post 9", "likes": 0, "dislikes": 0 },
    { "id": 10, "category": {"id": 5, "name": "Препод"}, "author_id": 10, "name": "Post 10", "body": "Body of post 10", "likes": 15, "dislikes": 1 },
    { "id": 11, "category": {"id": 5, "name": "Препод"}, "author_id": 11, "name": "Post 11", "body": "Body of post 11", "likes": 4, "dislikes": 3 },
    { "id": 1, "category": {"id": 6, "name": "Отзыв"}, "author_id": 1, "name": "1", "body": "Спокойный, уравновешенный препод, на лекциях дает очень структурированный материал. Зачастую не пускает в аудиторию при опоздании более чем на 15 минут. В начале обучения может быть очень тяжело и непонятно, но к преподу нужно привыкнуть", "likes": 5, "dislikes": 1 },
    { "id": 2, "category": {"id": 6, "name": "Отзыв"}, "author_id": 2, "name": "1", "body": "Body of post 2", "likes": 3, "dislikes": 2 },
    { "id": 3, "category": {"id": 6, "name": "Отзыв"}, "author_id": 3, "name": "1", "body": "Body of post 3", "likes": 12, "dislikes": 4 },
    { "id": 4, "category": {"id": 6, "name": "Отзыв"}, "author_id": 4, "name": "1", "body": "Body of post 4", "likes": 7, "dislikes": 0 },
    { "id": 5, "category": {"id": 6, "name": "Отзыв"}, "author_id": 5, "name": "1", "body": "Body of post 5", "likes": 8, "dislikes": 1 },
    { "id": 6, "category": {"id": 6, "name": "Отзыв"}, "author_id": 6, "name": "1", "body": "Body of post 6", "likes": 2, "dislikes": 0 },
    { "id": 7, "category": {"id": 6, "name": "Отзыв"}, "author_id": 7, "name": "1", "body": "Body of post 7", "likes": 10, "dislikes": 5 },
    { "id": 8, "category": {"id": 6, "name": "Отзыв"}, "author_id": 8, "name": "1", "body": "Body of post 8", "likes": 6, "dislikes": 2 },
    { "id": 9, "category": {"id": 6, "name": "Отзыв"}, "author_id": 9, "name": "1", "body": "Body of post 9", "likes": 0, "dislikes": 0 },
    { "id": 10, "category": {"id": 6, "name": "Отзыв"}, "author_id": 10, "name": "1", "body": "Body of post 10", "likes": 15, "dislikes": 1 },
    { "id": 11, "category": {"id": 6, "name": "Отзыв"}, "author_id": 11, "name": "1", "body": "Body of post 11", "likes": 4, "dislikes": 3 },
]
export default posts;