[{ "id": 1, "category": {"id": 6, "name": "Отзыв"}, "author_id": 1, "name": "1", "body": "Спокойный, уравновешенный препод, на лекциях дает очень структурированный материал. Зачастую не пускает в аудиторию при опоздании более чем на 15 минут. В начале обучения может быть очень тяжело и непонятно, но к преподу нужно привыкнуть", "likes": 5, "dislikes": 1 },
    { "id": 2, "category": {"id": 6, "name": "Отзыв"}, "author_id": 2, "name": "1", "body": "Body of post 2", "likes": 3, "dislikes": 2 },
    { "id": 3, "category": {"id": 6, "name": "Отзыв"}, "author_id": 3, "name": "1", "body": "Body of post 3", "likes": 12, "dislikes": 4 },
    { "id": 4, "category": {"id": 6, "name": "Отзыв"}, "author_id": 4, "name": "1", "body": "Body of post 4", "likes": 7, "dislikes": 0 },
    { "id": 5, "category": {"id": 6, "name": "Отзыв"}, "author_id": 5, "name": "1", "body": "Body of post 5", "likes": 8, "dislikes": 1 },
    { "id": 6, "category": {"id": 6, "name": "Отзыв"}, "author_id": 6, "name": "1", "body": "Body of post 6", "likes": 2, "dislikes": 0 },
    { "id": 7, "category": {"id": 6, "name": "Отзыв"}, "author_id": 7, "name": "1", "body": "Body of post 7", "likes": 10, "dislikes": 5 },
    { "id": 8, "category": {"id": 6, "name": "Отзыв"}, "author_id": 8, "name": "1", "body": "Body of post 8", "likes": 6, "dislikes": 2 },
    { "id": 9, "category": {"id": 6, "name": "Отзыв"}, "author_id": 9, "name": "1", "body": "Body of post 9", "likes": 0, "dislikes": 0 },
    { "id": 10, "category": {"id": 6, "name": "Отзыв"}, "author_id": 10, "name": "1", "body": "Body of post 10", "likes": 15, "dislikes": 1 },
    { "id": 11, "category": {"id": 6, "name": "Отзыв"}, "author_id": 11, "name": "1", "body": "Body of post 11", "likes": 4, "dislikes": 3 },
]