const users = [
    { "author_id": 1, "name": "user1", "password": "string", "is_admin": true },
    { "author_id": 2, "name": "user2", "password": "string", "is_admin": false },
    { "author_id": 3, "name": "user3", "password": "string", "is_admin": true },
    { "author_id": 4, "name": "user4", "password": "string", "is_admin": false },
    { "author_id": 5, "name": "user5", "password": "string", "is_admin": true },
    { "author_id": 6, "name": "user6", "password": "string", "is_admin": false },
    { "author_id": 7, "name": "user7", "password": "string", "is_admin": true },
    { "author_id": 8, "name": "user8", "password": "string", "is_admin": false },
    { "author_id": 9, "name": "user9", "password": "string", "is_admin": true },
    { "author_id": 10, "name": "user10", "password": "string", "is_admin": false },
    { "author_id": 11, "name": "user11", "password": "string", "is_admin": false },
    { "author_id": 12, "name": "user12", "password": "string", "is_admin": true },
    { "author_id": 13, "name": "user13", "password": "string", "is_admin": false },
    { "author_id": 14, "name": "user14", "password": "string", "is_admin": true },
    { "author_id": 15, "name": "user15", "password": "string", "is_admin": false },
    { "author_id": 16, "name": "user16", "password": "string", "is_admin": false },
    { "author_id": 17, "name": "user17", "password": "string", "is_admin": true },
    { "author_id": 18, "name": "user18", "password": "string", "is_admin": true },
    { "author_id": 19, "name": "user19", "password": "string", "is_admin": false },
    { "author_id": 20, "name": "user20", "password": "string", "is_admin": true },
    { "author_id": 21, "name": "user21", "password": "string", "is_admin": false },
    { "author_id": 22, "name": "user22", "password": "string", "is_admin": true },
    { "author_id": 23, "name": "user23", "password": "string", "is_admin": false },
    { "author_id": 24, "name": "user24", "password": "string", "is_admin": true },
    { "author_id": 25, "name": "user25", "password": "string", "is_admin": false },
    { "author_id": 26, "name": "user26", "password": "string", "is_admin": false },
    { "author_id": 27, "name": "user27", "password": "string", "is_admin": true },
    { "author_id": 28, "name": "user28", "password": "string", "is_admin": true },
    { "author_id": 29, "name": "user29", "password": "string", "is_admin": false },
    { "author_id": 30, "name": "user30", "password": "string", "is_admin": true },
    { "author_id": 31, "name": "user31", "password": "string", "is_admin": false },
    { "author_id": 32, "name": "user32", "password": "string", "is_admin": true },
    { "author_id": 33, "name": "user33", "password": "string", "is_admin": false },
    { "author_id": 34, "name": "user34", "password": "string", "is_admin": true },
    { "author_id": 35, "name": "user35", "password": "string", "is_admin": false },
    { "author_id": 36, "name": "user36", "password": "string", "is_admin": true },
    { "author_id": 37, "name": "user37", "password": "string", "is_admin": false },
    { "author_id": 38, "name": "user38", "password": "string", "is_admin": true },
    { "author_id": 39, "name": "user39", "password": "string", "is_admin": false },
    { "author_id": 40, "name": "user40", "password": "string", "is_admin": true }
  ]

export default users;